--------------------------------------------------------
--  DDL for Table STUDENTSURVEY
--------------------------------------------------------

  CREATE TABLE "ADMIN"."STUDENTSURVEY" 
   (	"STUDENTSURVEYID" NUMBER(*,0), 
	"USERID" NUMBER(*,0), 
	"HASTAKENSURVEY" NUMBER(1,0), 
	"SURVEYCOMPLETIONDATE" DATE, 
	"RESULT" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"NUMBEROFREMINDERSSENT" NUMBER(*,0), 
	"LASTEMAILSENDDATE" DATE, 
	"LASTEMAILSENDSTATUS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAILTYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"RESULTSSENT" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0031541
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0031541" ON "ADMIN"."STUDENTSURVEY" ("STUDENTSURVEYID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table STUDENTSURVEY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."STUDENTSURVEY" ADD PRIMARY KEY ("STUDENTSURVEYID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENTSURVEY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."STUDENTSURVEY" ADD FOREIGN KEY ("USERID")
	  REFERENCES "ADMIN"."USERS" ("USERID") ENABLE;

--------------------------------------------------------
--  DDL for Table SURVEYQUESTION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SURVEYQUESTION" 
   (	"SURVEYQUESTIONID" NUMBER(*,0), 
	"QUESTIONTYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"QUESTION" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0031543
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0031543" ON "ADMIN"."SURVEYQUESTION" ("SURVEYQUESTIONID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table SURVEYQUESTION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SURVEYQUESTION" ADD PRIMARY KEY ("SURVEYQUESTIONID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

--------------------------------------------------------
--  DDL for Table SURVEYQUESTIONRESPONSES
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SURVEYQUESTIONRESPONSES" 
   (	"STUDENTSURVEYID" NUMBER(*,0), 
	"SURVEYQUESTIONID" NUMBER(*,0), 
	"RESPONSE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0031544
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0031544" ON "ADMIN"."SURVEYQUESTIONRESPONSES" ("STUDENTSURVEYID", "SURVEYQUESTIONID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table SURVEYQUESTIONRESPONSES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SURVEYQUESTIONRESPONSES" ADD PRIMARY KEY ("STUDENTSURVEYID", "SURVEYQUESTIONID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SURVEYQUESTIONRESPONSES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SURVEYQUESTIONRESPONSES" ADD FOREIGN KEY ("STUDENTSURVEYID")
	  REFERENCES "ADMIN"."STUDENTSURVEY" ("STUDENTSURVEYID") ENABLE;

--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."USERS" 
   (	"USERID" NUMBER(*,0), 
	"PASSWORD" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ISFIRSTLOGIN" NUMBER(1,0), 
	"ISADMIN" NUMBER(1,0), 
	"FIRSTNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LASTNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SEMESTERID" NUMBER(*,0), 
	"ISSURVEYELIGIBLE" NUMBER(1,0), 
	"UNIVERSITYID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0031539
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0031539" ON "ADMIN"."USERS" ("USERID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."USERS" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."USERS" ADD CONSTRAINT "FK_SEMESTER" FOREIGN KEY ("SEMESTERID")
	  REFERENCES "ADMIN"."SEMESTER" ("SEMESTERID") ENABLE;
--------------------------------------------------------
--  DDL for Table SEMESTER
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SEMESTER" 
   (	"SEMESTERID" NUMBER(*,0), 
	"YEAR" NUMBER(*,0), 
	"SEASON" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0031538
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0031538" ON "ADMIN"."SEMESTER" ("SEMESTERID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table SEMESTER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SEMESTER" ADD PRIMARY KEY ("SEMESTERID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

--------------------------------------------------------
--  DDL for Table EMAILTEMPLATE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."EMAILTEMPLATE" 
   (	"EMAILTEMPLATEID" NUMBER(*,0), 
	"EMAILTYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAILSUBJECT" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAILBODYHTML" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0031548
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0031548" ON "ADMIN"."EMAILTEMPLATE" ("EMAILTEMPLATEID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table EMAILTEMPLATE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EMAILTEMPLATE" ADD PRIMARY KEY ("EMAILTEMPLATEID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  DDL for Table HIGHRISKCOUNTRIES
--------------------------------------------------------

  CREATE TABLE "ADMIN"."HIGHRISKCOUNTRIES" 
   (	"COUNTRYID" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRYNAME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0031547
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0031547" ON "ADMIN"."HIGHRISKCOUNTRIES" ("COUNTRYID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table HIGHRISKCOUNTRIES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."HIGHRISKCOUNTRIES" ADD PRIMARY KEY ("COUNTRYID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
